### ISSUE TITLE
Link to regulation A4b1

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/wca.link#7]
For example link to A7g works correctly, but link to A4b1 — not. Maybe another Regulations have this problem too, I don't know
https://wca.link/A7g
https://wca.link/A4b1

**Comment by jfly** [comment]
For the record, `https://wca.link/A4b1` is currently redirecting to `https://www.worldcubeassociation.org/regulations/guidelines.html#A4b11` (note the b11 instead of b1):

```
$ curl -is https://wca.link/A4b1 | grep -i location
location: https://www.worldcubeassociation.org/regulations/guidelines.html#A4b11
```

The relevant code is [here](https://github.com/thewca/wca.link/blob/4ae3040f7585dc7827a5d6aa68903f8c5b226f63/lambda_function.rb#L31). You can see it misbehaving here:

```ruby
$ irb
irb(main):001:0> location = "/A4b1"
=> "/A4b1"
irb(main):003:0> /^\/([0-9]{1,2}[a-z]([0-9]{1,2}[a-z]?)?|[A-Z][0-9]{1,2}([a-z]([0-9]{1,2})?)?)(\+*)$/.match(location)
=> #<MatchData "/A4b1" 1:"A4b1" 2:nil 3:"b1" 4:"1" 5:"">
irb(main):004:0> 
```

I do not have time right now to try to understand that regex =)
